### ISSUE TITLE
New translations for English

### ISSUE THREAD

**Issue by tesseralis** [tesseralis-fan-club/tesseralis.club#8]
Hello, this is dog. I want to do English dog. Yes, dog.

```yaml
name: English
code: en
maintainers:
 - tesseralis
 - marcysutton
```

Additional text that doesn't matter.
